#!/usr/bin/env python3
"""Regenerate adr/INDEX.yaml from adr/LOG.yaml.

Usage:
    python3 scripts/adr-index.py          # from repo root
    make adr-index                         # via Makefile target

Pre-commit hook (optional):
    echo 'python3 scripts/adr-index.py && git add adr/INDEX.yaml' \\
        >> .git/hooks/pre-commit
    chmod +x .git/hooks/pre-commit

Status values:
    proposed   — open for objection window
    ratified   — binding in its scope
    superseded — replaced by a later ADR (include superseded_by)
    withdrawn  — retracted before ratification
    CARRIED    — ratified-at-origin, proposed-at-platform

SCOPED-binding fields:
    An ADR may carry both origin_status and platform_status when ratified
    at the authoring repo but not yet extended across all platform repos.
    INDEX supports filtering by platform_status: ratified.
"""

from pathlib import Path
import yaml

REPO_ROOT = Path(__file__).parent.parent
LOG_PATH = REPO_ROOT / "adr" / "LOG.yaml"
INDEX_PATH = REPO_ROOT / "adr" / "INDEX.yaml"

HEADER = """\
# LandVault Governance Corpus — ADR Index (compact scan-file)
#
# Generated by scripts/adr-index.py — run `make adr-index` to regenerate
# after editing LOG.yaml.
#
# Agents: read this file first. Filter to `platform_status: ratified` for
# platform-binding decisions. Filter to `origin_status: ratified` for
# decisions ratified at their authoring repo. Match `tags` against the
# current task. Read the full entry from LOG.yaml only when a tag or
# keyword matches.
#
# Format per entry:
#   { id, status, tags, title[, origin_status, platform_status, superseded_by] }"""

# YAML flow-scalar characters that require quoting.
_FIRST_CHAR_UNSAFE = set('\'"{}[]|>&!%@`*-?:#. ')


def scalar(s: str) -> str:
    """Format s as a quoted-only-when-necessary YAML flow scalar."""
    if (
        not s
        or s[0] in _FIRST_CHAR_UNSAFE
        or ': ' in s
        or s.endswith(':')
        or ' #' in s
        or s.lower() in ('true', 'false', 'null', 'yes', 'no', 'on', 'off', '~')
    ):
        return "'" + s.replace("'", "''") + "'"
    return s


def fmt_tags(tags: list) -> str:
    return "[" + ", ".join(str(t) for t in tags) + "]"


def fmt_entry(e: dict) -> str:
    parts = [
        f"id: {scalar(e['id'])}",
        f"status: {scalar(e['status'])}",
        f"tags: {fmt_tags(e.get('tags', []))}",
        f"title: {scalar(e['title'])}",
    ]
    # SCOPED-binding fields — present when the ADR has separate origin and
    # platform scope statuses (e.g., ratified-at-origin, proposed-at-platform).
    if "origin_status" in e:
        parts.append(f"origin_status: {scalar(e['origin_status'])}")
    if "platform_status" in e:
        parts.append(f"platform_status: {scalar(e['platform_status'])}")
    if "superseded_by" in e:
        parts.append(f"superseded_by: {scalar(e['superseded_by'])}")
    return "- { " + ", ".join(parts) + " }"


def main() -> None:
    if not LOG_PATH.exists():
        raise SystemExit(f"LOG.yaml not found at {LOG_PATH}")

    raw = LOG_PATH.read_text().strip()
    # An empty or comment-only log is valid — the corpus starts with no ADRs.
    if not raw or all(line.startswith('#') for line in raw.splitlines()):
        entries = []
    else:
        entries = yaml.safe_load(raw)
        if entries is None:
            entries = []
        if not isinstance(entries, list):
            raise SystemExit("LOG.yaml must be a YAML list of ADR entries")

    VALID_STATUSES = {"proposed", "ratified", "superseded", "withdrawn", "CARRIED"}
    for entry in entries:
        status = entry.get("status", "")
        if status not in VALID_STATUSES:
            raise SystemExit(
                f"Invalid status {status!r} in entry {entry.get('id', '(unknown id)')!r}. "
                f"Must be one of: {', '.join(sorted(VALID_STATUSES))}"
            )

    lines = [HEADER, ""]
    for entry in entries:
        lines.append(fmt_entry(entry))
    if not entries:
        lines.append("# LOG.yaml is empty — no ADR entries yet.")

    INDEX_PATH.write_text("\n".join(lines) + "\n")
    print(f"Regenerated INDEX.yaml — {len(entries)} entries")


if __name__ == "__main__":
    main()
